### PR TITLE
chore: roll driver, fix driver wait until exit

### PR DESCRIPTION
**Pull request by kumaraditya303**
FIxes https://github.com/mxschmitt/playwright-go/issues/209

### CODE REVIEW

**Review by mxschmitt — APPROVED** [review]

**Comment by mxschmitt** [comment]
For the record: The `NODE_OPTIONS` thing was from the old days when using `@vercel/pkg` to create the driver. This was not incompatible with the `NODE_OPTIONS` environment variable which came from e.g. a Visual Studio Code Debugging Terminal.

**Comment by kumaraditya303** [comment]
Is there something which can rerun the flaky tests in golang ?

**Comment by kumaraditya303** [comment]
@mxschmitt merge

**Comment by kumaraditya303** [comment]
@KiqoCode until a new release you install with the latest git commit with go get see https://stackoverflow.com/questions/53682247/how-to-point-go-module-dependency-in-go-mod-to-a-latest-commit-in-a-repo

**Pull request merged**
