### PR TITLE
add ElementHandle.WaitForElementState/WaitForSelector methods

### PR DESCRIPTION
**Pull request by lcmtwn**
Relates #34 

ElementHandle.WaitForElementState
ElementHandle.WaitForSelector

### CODE REVIEW

**Comment by mxschmitt** [comment]
Would be cool if you could remove the `|| true` in the `scripts/generate-api.sh` so its enforced then.

**Comment by lcmtwn** [comment]
> Would be cool if you could remove the `|| true` in the `scripts/generate-api.sh` so its enforced then.

updated

**Review by mxschmitt — APPROVED** [review]
LGTM

**Comment by mxschmitt** [comment]
thank you! :)

**Pull request merged**
