### PR TITLE
chore: add verbose mode to downloader

### PR DESCRIPTION
**Pull request by kumaraditya303**
Fixes https://github.com/mxschmitt/playwright-go/issues/144

### CODE REVIEW

**Comment by mxschmitt** [comment]
Not sure if we should add verbose: bool vs. Logger: someLoggerInterface

**Comment by kumaraditya303** [comment]
> Not sure if we should add verbose: bool vs. Logger: someLoggerInterface

Verbose is enough for now, logging can be added later on.

**Review by mxschmitt — APPROVED** [review]

**Comment by kumaraditya303** [comment]
@mxschmitt merge

**Comment by mxschmitt** [comment]
Unrelated to this PR, the following test is flaky:

```
=== RUN   TestShouldReportResponseHeadersArray
    network_test.go:161: 
        	Error Trace:	network_test.go:161
        	Error:      	Not equal: 
        	            	expected: "a=b\nc=d"
        	            	actual  : "c=d\na=b"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	+c=d
        	            	 a=b
        	            	-c=d
        	Test:       	TestShouldReportResponseHeadersArray
--- FAIL: TestShouldReportResponseHeadersArray (0.24s)
```

**Pull request merged**
